name = "ai-chat-woker"
main = "src/index.js"
compatibility_date = "2024-01-15"

# 环境变量配置
[vars]
# 这里可以设置默认的环境变量

# 生产环境配置
[env.production]
name = "openai-graphql-worker-prod"

# 开发环境配置  
[env.dev]
name = "openai-graphql-worker-dev"